### ISSUE TITLE
clear loop

### ISSUE THREAD

**Issue by andrew-davie** [JeffJetton/atari-examples#11]
In https://github.com/JeffJetton/atari-examples/blob/master/bbones/bbones3.md where you discuss hitting $FF on the clear loop, and having to stop... this is incorrect.

In fact, when you "inx" it wraps back to 0, so you don't need the "cpx #$FF" in the loop - you just do a bne, and you don't need that final "sty $FF" because it will be cleared by the loop operating 256 times.

**Comment by JeffJetton** [comment]
Yeah, that would be more efficient, and I'm giving it a bit of a rewrite per issue #14. But my goal here is to implement it in a more idiomatically high-level language way at first, just to give someone coming from another language some territory that's only _slightly_ foreign. I get into a more "assembly-like" method in the next example. And, of course, it all eventually gets replaced by your macro later! :-)

I'll try to be more clear that this is an inefficient, temporary, way of doing it. Maybe that will help?

**Comment by JeffJetton** [comment]
I see that it currently might also be giving the impression that you _can't_ increment $FF. I'll clarify that too...

**Comment by andrew-davie** [comment]
The CLEAN_START macro was actually written by some weird alien intelligence.
It's quite bizarre.
