### ISSUE TITLE
can't do comparison!

### ISSUE THREAD

**Issue by andrew-davie** [JeffJetton/atari-examples#14]
in bbones3, the clear loop, you say...
"So that's what we do. We can't do a comparison on the X register--only the A register. So we first have to Transfer X to A."

This is totally wrong. You CAN do comparisons on the X register.
"cpx #$FF" is totally valid.

This comment definitely needs to be fixed, and the code could of course be more efficient.

**Comment by JeffJetton** [comment]
Doh! What was I thinking. Rewriting...
